# environment.yml

name: readthedocs # this is just a name for the environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - networkx
  - simpy
  - scipy
  - pip:
    - pyqt6